/**
 * Adapter for integration of Gardena Smart System to ioBroker
 * based on official GARDENA smart system API (https://developer.1689.cloud/)
 * Support:             https://forum.iobroker.net/...
 * Autor:               jpgorganizer (ioBroker) | jpgorganizer (github)
 * SVN:                 $Rev: 2028 $ ($Date: 2020-04-05 20:50:44 +0200 (So, 05 Apr 2020) $)
 * contains definitions of datapoints
 */


const gardenaServicesDataPoints = {SERVICE_COMMON: {
										name_value: {predefineForDevices: ['MOWER', 'POWER_SOCKET', 'VALVE_SET', 'VALVE', 'SENSOR'],
													commontype: 'string',
													commonrole: 'info.name',
													unit: 'none',
													iscommand: false,
													commonwrite: false},
										batteryLevel_value: {predefineForDevices: ['MOWER', 'SENSOR'],
													commontype: 'number',
													commonrole: 'value.battery',
													commonwrite: false,
													iscommand: false,
													unit: '%'},
										batteryLevel_timestamp: {predefineForDevices: ['MOWER', 'SENSOR'],
													commontype: 'string',
													commonrole: 'date',
													commonwrite: false,
													iscommand: false,
													unit: 'none'},
										batteryState_value: {predefineForDevices: ['MOWER', 'POWER_SOCKET', 'VALVE_SET', 'VALVE', 'SENSOR'],
													commontype: 'string',
													commonrole: 'info.status',
													commonwrite: false,
													iscommand: false,
													unit: 'none'},
										batteryState_timestamp: {predefineForDevices: ['MOWER', 'SENSOR'],
													commontype: 'string',
													commonrole: 'date',
													commonwrite: false,
													iscommand: false,
													unit: 'none'},
										rfLinkLevel_value: {predefineForDevices: ['MOWER', 'POWER_SOCKET', 'VALVE_SET', 'VALVE', 'SENSOR'],
													commontype: 'number',
													commonrole: 'value',
													commonwrite: false,
													iscommand: false,
													unit: 'none'},
										rfLinkLevel_timestamp: {predefineForDevices: ['MOWER', 'POWER_SOCKET', 'VALVE_SET', 'VALVE', 'SENSOR'],
													commontype: 'string',
													commonrole: 'date',
													commonwrite: false,
													iscommand: false,
													unit: 'none'},
										serial_value: {predefineForDevices: ['MOWER', 'POWER_SOCKET', 'VALVE_SET', 'VALVE', 'SENSOR'],
													commontype: 'string',
													commonrole: 'text',
													commonwrite: false,
													iscommand: false,
													unit: 'none'},
										modelType_value: {predefineForDevices: ['MOWER', 'POWER_SOCKET', 'VALVE_SET', 'VALVE', 'SENSOR'],
													commontype: 'string',
													commonrole: 'text',
													commonwrite: false,
													iscommand: false,
													unit: 'none'},
										rfLinkState_value: {predefineForDevices: ['MOWER', 'POWER_SOCKET', 'VALVE_SET', 'VALVE', 'SENSOR'],
													commontype: 'string',
													commonrole: 'info.status',
													commonwrite: false,
													iscommand: false,
													unit: 'none'},
										rfLinkState_timestamp: {predefineForDevices: ['MOWER', 'POWER_SOCKET', 'VALVE_SET', 'VALVE', 'SENSOR'],
													commontype: 'string',
													commonrole: 'date',
													commonwrite: false,
													iscommand: false,
													unit: 'none'}
										},
						 SERVICE_MOWER: {
										state_value: {predefineForDevices: ['MOWER'],
													commontype: 'string',
													commonrole: 'info.status',
													unit: 'none',
													iscommand: false,
													commonwrite: false},
										state_timestamp: {predefineForDevices: ['MOWER'],
													commontype: 'string',
													commonrole: 'date',
													unit: 'none',
													iscommand: false,
													commonwrite: false},
										activity_value: {predefineForDevices: ['MOWER'],
													commontype: 'string',
													commonrole: 'info.status',
													unit: 'none',
													iscommand: false,
													commonwrite: false},
										activity_timestamp: {predefineForDevices: ['MOWER'],
													commontype: 'string',
													commonrole: 'date',
													unit: 'none',
													iscommand: false,
													commonwrite: false},
										lastErrorCode_value: {predefineForDevices: ['MOWER'],
													commontype: 'string',
													commonrole: 'text',
													unit: 'none',
													iscommand: false,
													commonwrite: false},
										lastErrorCode_timestamp: {predefineForDevices: ['MOWER'],
													commontype: 'string',
													commonrole: 'date',
													unit: 'none',
													iscommand: false,
													commonwrite: false},
										operatingHours_value: {predefineForDevices: ['MOWER'],
													commontype: 'number^',
													commonrole: 'value',
													unit: 'none',
													iscommand: false,
													commonwrite: false}										
										},
						 SERVICE_POWER_SOCKET: {
										state_value: {predefineForDevices: ['POWER_SOCKET'],
						 							commontype: 'string',
						 							commonrole: 'info.status',
						 							unit: 'none',
													iscommand: false,
						 							commonwrite: false},
						 				state_timestamp: {predefineForDevices: ['POWER_SOCKET'],
						 							commontype: 'string',
						 							commonrole: 'date',
						 							unit: 'none',
													iscommand: false,
						 							commonwrite: false},
						 				activity_value: {predefineForDevices: ['POWER_SOCKET'],
						 							commontype: 'string',
						 							commonrole: 'info.status',
						 							unit: 'none',
													iscommand: false,
						 							commonwrite: false},
						 				activity_timestamp: {predefineForDevices: ['POWER_SOCKET'],
						 							commontype: 'string',
						 							commonrole: 'date',
						 							unit: 'none',
													iscommand: false,
						 							commonwrite: false},
						 				lastErrorCode_value: {predefineForDevices: ['POWER_SOCKET'],
						 							commontype: 'string',
						 							commonrole: 'text',
						 							unit: 'none',
													iscommand: false,
						 							commonwrite: false},
						 				lastErrorCode_timestamp: {predefineForDevices: ['POWER_SOCKET'],
						 							commontype: 'string',
						 							commonrole: 'date',
						 							unit: 'none',
													iscommand: false,
						 							commonwrite: false},
						 				duration_value: {predefineForDevices: ['POWER_SOCKET'],
						 							commontype: 'string',
						 							commonrole: 'text',
						 							unit: 'none',
													iscommand: true,
						 							commonwrite: true},
						 				duration_timestamp: {predefineForDevices: ['POWER_SOCKET'],
						 							commontype: 'string',
						 							commonrole: 'date',
						 							unit: 'none',
													iscommand: false,
						 							commonwrite: false}						
						 				},
						SERVICE_SENSOR: {
										soilHumidity_value: {predefineForDevices: ['SENSOR'],
						 							commontype: 'number',
						 							commonrole: 'value.humidity',
						 							unit: '%',
													iscommand: false,
						 							commonwrite: false},
						 				soilHumidity_timestamp: {predefineForDevices: ['SENSOR'],
						 							commontype: 'string',
						 							commonrole: 'date',
						 							unit: 'none',
													iscommand: false,
						 							commonwrite: false},
						 				soilTemperature_value: {predefineForDevices: ['SENSOR'],
						 							commontype: 'number',
						 							commonrole: 'value.temperature',
						 							unit: '°C',
													iscommand: false,
						 							commonwrite: false},
						 				soilTemperature_timestamp: {predefineForDevices: ['SENSOR'],
						 							commontype: 'string',
						 							commonrole: 'date',
						 							unit: 'none',
													iscommand: false,
						 							commonwrite: false},
						 				ambientTemperature_value: {predefineForDevices: ['SENSOR'],
						 							commontype: 'number',
						 							commonrole: 'value',
						 							unit: '°C',
													iscommand: false,
						 							commonwrite: false},
						 				ambientTemperature_timestamp: {predefineForDevices: ['SENSOR'],
						 							commontype: 'string',
						 							commonrole: 'date',
						 							unit: 'none',
													iscommand: false,
						 							commonwrite: false},
						 				lightIntensity_value: {predefineForDevices: ['SENSOR'],
						 							commontype: 'number',
						 							commonrole: 'value.brightness',
						 							unit: 'Lux',
													iscommand: false,
						 							commonwrite: false},
						 				lightIntensity_timestamp: {predefineForDevices: ['SENSOR'],
						 							commontype: 'string',
						 							commonrole: 'date',
						 							unit: 'none',
													iscommand: false,
						 							commonwrite: false},
						 				},
						SERVICE_VALVE: {
										name_value: {predefineForDevices: ['VALVE'],
						 							commontype: 'string',
						 							commonrole: 'info.name',
						 							unit: 'none',
													iscommand: false,
						 							commonwrite: false},
						 				activity_value: {predefineForDevices: ['VALVE'],
						 							commontype: 'string',
						 							commonrole: 'info.status',
						 							unit: 'none',
													iscommand: false,
						 							commonwrite: false},
						 				activity_timestamp: {predefineForDevices: ['VALVE'],
						 							commontype: 'string',
						 							commonrole: 'date',
						 							unit: 'none',
													iscommand: false,
						 							commonwrite: false},
						 				state_value: {predefineForDevices: ['VALVE'],
						 							commontype: 'string',
						 							commonrole: 'info.status',
						 							unit: 'none',
													iscommand: false,
						 							commonwrite: false},
						 				state_timestamp: {predefineForDevices: ['VALVE'],
						 							commontype: 'string',
						 							commonrole: 'date',
						 							unit: 'none',
													iscommand: false,
						 							commonwrite: false},
						 				lastErrorCode_value: {predefineForDevices: ['VALVE'],
						 							commontype: 'string',
						 							commonrole: 'text',
						 							unit: 'none',
													iscommand: false,
						 							commonwrite: false},
						 				lastErrorCode_timestamp: {predefineForDevices: ['VALVE'],
						 							commontype: 'string',
						 							commonrole: 'date',
						 							unit: 'none',
													iscommand: false,
						 							commonwrite: false},
						 				duration_value: {predefineForDevices: ['VALVE'],
						 							commontype: 'string',
						 							commonrole: 'text',
						 							unit: 'none',
													iscommand: true,
						 							commonwrite: true},
						 				duration_timestamp: {predefineForDevices: ['VALVE'],
						 							commontype: 'string',
						 							commonrole: 'date',
						 							unit: 'none',
													iscommand: false,
						 							commonwrite: false}						
						 				},
						SERVICE_VALVE_SET: {
										state_value: {predefineForDevices: ['VALVE_SET'],
						 							commontype: 'string',
						 							commonrole: 'info.status',
						 							unit: 'none',
													iscommand: false,
						 							commonwrite: false},
						 				state_timestamp: {predefineForDevices: ['VALVE_SET'],
						 							commontype: 'string',
						 							commonrole: 'date',
						 							unit: 'none',
													iscommand: false,
						 							commonwrite: false},
						 				lastErrorCode_value: {predefineForDevices: ['VALVE_SET'],
						 							commontype: 'string',
						 							commonrole: 'text',
						 							unit: 'none',
													iscommand: false,
						 							commonwrite: false},
						 				lastErrorCode_timestamp: {predefineForDevices: ['VALVE_SET'],
						 							commontype: 'string',
						 							commonrole: 'date',
						 							unit: 'none',
													iscommand: false,
						 							commonwrite: false}
						 				}
						 };

						 
						 
module.exports = {
	gardenaServicesDataPoints: gardenaServicesDataPoints
}
