/*global systemDictionary:true */
"use strict";

systemDictionary = {
  "smartgarden adapter settings": {
    "en": "Adapter settings for smartgarden",
    "de": "Adaptereinstellungen für smartgarden",
    "ru": "Настройки адаптера для smartgarden",
    "pt": "Configurações do adaptador para smartgarden",
    "nl": "Adapterinstellingen voor smartgarden",
    "fr": "Paramètres d'adaptateur pour smartgarden",
    "it": "Impostazioni dell'adattatore per smartgarden",
    "es": "Ajustes del adaptador para smartgarden",
    "pl": "Ustawienia adaptera dla smartgarden",
    "zh-cn": "smartgarden的适配器设置"
  },
  "gardena_password": {
    "en": "Password",
    "de": "Passwort",
    "ru": "пароль",
    "pt": "Senha",
    "nl": "Wachtwoord",
    "fr": "Mot de passe",
    "it": "Parola d'ordine",
    "es": "Contraseña",
    "pl": "Hasło"
  },
  "gardena_username": {
    "en": "Username",
    "de": "Nutzername",
    "ru": "имя пользователя",
    "pt": "Nome de usuário",
    "nl": "Gebruikersnaam",
    "fr": "Nom d'utilisateur",
    "it": "Nome utente",
    "es": "Nombre de usuario",
    "pl": "Nazwa Użytkownika"
  },
  "gardena_api_key": {
    "en": "API key",
    "de": "API key",
    "ru": "Ключ API",
    "pt": "Chave API",
    "nl": "API sleutel",
    "fr": "Clé API",
    "it": "Chiave API",
    "es": "Clave API",
    "pl": "Klucz API",
    "zh-cn": "API密钥"
  },
  "gardena_authentication_host": {
    "en": "Auth-URL: Authentication host URL (https://api.authentication.husqvarnagroup.dev)",
    "de": "Auth-URL: Authentifizierungshost-URL (https://api.authentication.husqvarnagroup.dev)",
    "ru": "Auth-URL: URL хоста аутентификации (https://api.authentication.husqvarnagroup.dev)",
    "pt": "Auth-URL: URL do host de autenticação (https://api.authentication.husqvarnagroup.dev)",
    "nl": "Auth-URL: URL van authenticatiehost (https://api.authentication.husqvarnagroup.dev)",
    "fr": "Auth-URL: URL de l'hôte d'authentification (https://api.authentication.husqvarnagroup.dev)",
    "it": "Auth-URL: URL host di autenticazione (https://api.authentication.husqvarnagroup.dev)",
    "es": "Auth-URL: URL de host de autenticación (https://api.authentication.husqvarnagroup.dev)",
    "pl": "Auth-URL: Adres URL hosta uwierzytelniania (https://api.authentication.husqvarnagroup.dev)",
    "zh-cn": "Auth-URL: 认证主机URL (https://api.authentication.husqvarnagroup.dev)"
  },
  "gardena_ping_frequence": {
    "en": "ping frequence: Frequence for sending Ping's to Gardena Webservice (in seconds)",
    "de": "ping frequence: Häufigkeit für das Senden von Pings an Gardena Webservice (in Sekunden)",
    "ru": "ping frequence: Частота отправки Ping's в Gardena Webservice (в секундах)",
    "pt": "ping frequence: Frequência para o envio de ping para o Gardena Webservice (em segundos)",
    "nl": "ping frequence: Frequentie voor het verzenden van Ping's naar Gardena Webservice (in seconden)",
    "fr": "ping frequence: Fréquence d'envoi des Ping à Gardena Webservice (en secondes)",
    "it": "ping frequence: Frequenza per l'invio di ping a Gardena Webservice (in secondi)",
    "es": "ping frequence: Frecuencia para enviar Ping's al servicio web de Gardena (en segundos)",
    "pl": "ping frequence: Częstotliwość wysyłania pingów do Gardena Webservice (w sekundach)",
    "zh-cn": "ping frequence: 将Ping发送到Gardena Webservice的频率（以秒为单位）"
  },
  "gardena_authtoken_factor": {
    "en": "auth factor: Factor for validity of authentication token",
    "de": "auth factor: Faktor für die Gültigkeit des Authentifizierungstokens",
    "ru": "auth factor: Коэффициент достоверности токена аутентификации",
    "pt": "auth factor: Fator de validade do token de autenticação",
    "nl": "auth factor: Factor voor geldigheid van authenticatietoken",
    "fr": "auth factor: Facteur de validité du jeton d'authentification",
    "it": "auth factor: Fattore di validità del token di autenticazione",
    "es": "auth factor: Factor para la validez del token de autenticación",
    "pl": "auth factor: Czynnik ważności tokena uwierzytelniającego",
    "zh-cn": "auth factor: 认证令牌有效性的因素"
  },
  "useIrrigationAllowedWhileMowing": {
    "en": "irrigation check: Use the check whether irrigation is allowed while mowing",
    "de": "irrigation check: Verwenden der Prüfung, ob Bewässerung während dem Mähen erlaubt ist",
    "ru": "irrigation check: Используйте проверку, разрешено ли орошение во время кошения",
    "pt": "irrigation check: Verifique se a irrigação é permitida durante o corte",
    "nl": "irrigation check: Gebruik de controle of irrigatie is toegestaan tijdens het maaien",
    "fr": "irrigation check: Utilisez la vérification si l'irrigation est autorisée pendant la tonte",
    "it": "irrigation check: Utilizzare il controllo se l'irrigazione è consentita durante la falciatura",
    "es": "irrigation check: Use el control si el riego está permitido mientras corta",
    "pl": "irrigation check: Sprawdź, czy nawadnianie jest dozwolone podczas koszenia",
    "zh-cn": "irrigation check: 使用检查割草时是否允许灌溉"  
  },
  "useMowerHistory": {
    "en": "forecast: use forecast for charging time and mower remaining time",
    "de": "forecast: Verwenden Sie die Prognose für die Ladezeit und die verbleibende Zeit des Mähers",
    "ru": "forecast: использовать прогноз для времени зарядки и оставшегося времени косилки",
    "pt": "forecast: use a previsão para o tempo de carregamento e segure o tempo restante",
    "nl": "forecast: gebruik voorspelling voor laadtijd en resterende tijd van maaier",
    "fr": "forecast: utiliser les prévisions pour le temps de charge et le temps restant de la tondeuse",
    "it": "forecast: utilizzare le previsioni per il tempo di ricarica e il tempo rimanente del tagliaerba",
    "es": "forecast: use el pronóstico para el tiempo de carga y el tiempo restante de la segadora",
    "pl": "forecast: użyj prognozy czasu ładowania i pozostałego czasu pracy kosiarki",
    "zh-cn": "forecast: 将预测用于充电时间和割草机剩余时间"
  },
  "MowerHistoryCycles": {
    "en": "cycles: number of MOWER history cycles",
    "de": "cycles: Anzahl der Zyklen in MOWER Historie",
    "ru": "cycles: количество циклов истории MOWER",
    "pt": "cycles: número de ciclos históricos do MOWER",
    "nl": "cycles: aantal geschiedeniscycli van de MAAIER",
    "fr": "cycles: nombre de cycles d'historique MOWER",
    "it": "cycles: numero di cicli storici MOWER",
    "es": "cycles: número de ciclos de historia de MOWER",
    "pl": "cycles: liczba cykli historii KOSIARKI",
    "zh-cn": "cycles: MOWER历史周期数"
  },
  "useTestVariable": {
    "en": "use test variable for debug",
    "de": "testVariable für Debug Zwecke",
    "ru": "используйте тестовую переменную для отладки",
    "pt": "use variável de teste para depuração",
    "nl": "gebruik testvariabele voor foutopsporing",
    "fr": "utiliser la variable de test pour le débogage",
    "it": "usa la variabile test per il debug",
    "es": "usar variable de prueba para depurar",
    "pl": "użyj zmiennej testowej do debugowania",
    "zh-cn": "使用测试变量进行调试"
  },
  "preDefineStates": {
    "en": "pre-define states: pre-define all states of Gardena API regardless they are currently transmitted",
    "de": "pre-define states: Definiere alle Zustände der Gardena-API vorab, unabhängig davon, ob sie aktuell übertragen werden",
    "ru": "pre-define states: предварительно определить все состояния API Gardena независимо от того, передаются ли они в данный момент",
    "pt": "pre-define states: pré-defina todos os estados da Gardena API, independentemente de serem transmitidos atualmente",
    "nl": "pre-define states: definieer vooraf alle staten van Gardena API, ongeacht of ze momenteel worden verzonden",
    "fr": "pre-define states: prédéfinir tous les états de l'API Gardena, quels qu'ils soient actuellement transmis",
    "it": "pre-define states: pre-definire tutti gli stati dell'API Gardena indipendentemente dal fatto che siano attualmente trasmessi",
    "es": "pre-define states: predefinir todos los estados de la API de Gardena independientemente de que se transmitan actualmente",
    "pl": "pre-define states: wstępnie zdefiniuj wszystkie stany interfejsu API Gardena, niezależnie od tego, które są aktualnie przesyłane",
    "zh-cn": "pre-define states: 预先定义Gardena API的所有状态，无论当前是否传输它们"
  },
  "logLevel": {
    "en": "Loglevel: 0 = no log, 1 = some logs, 2 = some more logs, 3 = all logs",
    "de": "Loglevel: 0 = no log, 1 = some logs, 2 = some more logs, 3 = all logs",
    "ru": "Уровень журнала: 0 = нет журнала, 1 = несколько журналов, 2 = еще несколько журналов, 3 = все журналы",
    "pt": "Nível de log: 0 = nenhum log, 1 = alguns logs, 2 = mais alguns logs, 3 = todos os logs",
    "nl": "Logniveau: 0 = geen log, 1 = enkele logs, 2 = nog enkele logs, 3 = alle logs",
    "fr": "Loglevel: 0 = aucun journal, 1 = certains journaux, 2 = quelques journaux supplémentaires, 3 = tous les journaux",
    "it": "Loglevel: 0 = nessun registro, 1 = alcuni registri, 2 = altri registri, 3 = tutti i registri",
    "es": "Loglevel: 0 = sin registro, 1 = algunos registros, 2 = algunos registros más, 3 = todos los registros",
    "pl": "Loglevel: 0 = brak dziennika, 1 = niektóre dzienniki, 2 = więcej dzienników, 3 = wszystkie dzienniki",
    "zh-cn": "日志级别：0 =无日志，1 =一些日志，2 =更多日志，3 =所有日志"
  },
  "monitoringRateLimits": {
    "en": "monitoring Rate Limits: monitor rate limits of Gardena smart system API",
    "de": "monitoring Rate Limits: Überwachen Sie die Zugriffsbeschränkungen der Gardena Smart System API",
    "ru": "monitoring Rate Limits: контролировать лимиты скорости API интеллектуальной системы Gardena",
    "pt": "monitoring Rate Limits: monitorar limites de taxa de API do sistema inteligente Gardena",
    "nl": "monitoring Rate Limits: bewaak de snelheidslimieten van de Gardena slimme systeem-API",
    "fr": "monitoring Rate Limits: surveiller les limites de débit de l'API Gardena Smart System",
    "it": "monitoring Rate Limits: monitorare i limiti di velocità dell'API del sistema intelligente Gardena",
    "es": "monitoring Rate Limits: supervisar los límites de velocidad de la API del sistema inteligente de Gardena",
    "pl": "monitoring Rate Limits: monitorowanie limitów szybkości Gardena smart system API",
    "zh-cn": "monitoring Rate Limits: 监视Gardena智能系统API的速率限制"  },
  "smart_host": {
    "en": "Base-URL: Webservice Base-URL (https://api.smart.gardena.dev)",
    "de": "Base-URL: Webservice Basis-URL (https://api.smart.gardena.dev)",
    "ru": "Base-URL: URL-адрес веб-сервиса (https://api.smart.gardena.dev)",
    "pt": "Base-URL: Base de Webservice URL (https://api.smart.gardena.dev)",
    "nl": "Base-URL: Webservice Basis-URL (https://api.smart.gardena.dev)",
    "fr": "Base-URL: URL de base du service Web (https://api.smart.gardena.dev)",
    "it": "Base-URL: URL di base del servizio Web (https://api.smart.gardena.dev)",
    "es": "Base-URL: URL de base de servicio web (https://api.smart.gardena.dev)",
    "pl": "Base-URL: Webservice Basis-URL (https://api.smart.gardena.dev)",
    "zh-cn": "Base-URL: Webservice Basis-URL (https://api.smart.gardena.dev)"
  },
  "main settings": {
    "en": "main settings",
    "de": "Haupteinstellungen",
    "ru": "Основные параметры",
    "pt": "configurações principais",
    "nl": "belangrijkste instellingen",
    "fr": "Réglages principaux",
    "it": "impostazioni principali",
    "es": "ajustes principales",
    "pl": "Ustawienia główne"
  },
  "system_settings": {
    "en": "system settings",
    "de": "Systemeinstellungen",
    "ru": "настройки системы",
    "pt": "configurações do sistema",
    "nl": "systeem instellingen",
    "fr": "les paramètres du système",
    "it": "Impostazioni di sistema",
    "es": "ajustes del sistema",
    "pl": "Ustawienia systemowe",
    "zh-cn": "系统设置"
  },
  "miscellaneous": {
    "en": "Miscellaneous",
    "de": "Verschiedenes",
    "ru": "Разнообразный",
    "pt": "Diversos",
    "nl": "Diversen",
    "fr": "Divers",
    "it": "miscellaneo",
    "es": "Diverso",
    "pl": "Różne",
    "zh-cn": "杂"
  }
};